### ISSUE TITLE
Fixed some minor issues but stuck at Mirror drive

### ISSUE THREAD

**Issue by n9lsjr** [holepunchto/bare-dev#12]
Very impressive stuff you guys are building.
I'm testing
https://github.com/holepunchto/pear-expo-hello-world
and i've encountered some issues. 
Some pre-info: I disabled the build processes for iOS because i do not have xcode 
![image](https://github.com/holepunchto/bare-dev/assets/64911460/231641b8-065f-43c8-bbb1-57984e665340)

1. 
On some windows machines it seems like you need to add { shell: true } to the sdk.manager process.
![image](https://github.com/holepunchto/bare-dev/assets/64911460/1cf0e7f8-df3b-45d5-b94e-4bcf7dc6ee93)
Otherwise I got EINVAL error.
![image](https://github.com/holepunchto/bare-dev/assets/64911460/ed029607-c9fc-463d-bb8c-0fbd2d9e8eee)

2:
I fixed the issue with execute_process with a hardcoded path ( The previous issue reported did not solve it for me )
![image](https://github.com/holepunchto/bare-dev/assets/64911460/629095dc-5d92-4906-a72b-2d9653a61eb6)
I seemed like the build process did not identify (WIN32) for my system by some odd reason ( logged the if/else statement ), and even though I changed the else condition to match the windows setting I still got the same error. 
![image](https://github.com/holepunchto/bare-dev/assets/64911460/d10369a8-80ba-4a52-9f20-645e950ab211)

3.
I was using the standard dependency 0.7 of bare dev ~ and it never cloned the prebuilds folder correctly and got stuck here: 
![image](https://github.com/holepunchto/bare-dev/assets/64911460/ac445926-540e-4d1f-9160-f456c725ca2b)
I then updated to the latest 0.10.4 and now it gets stuck at here.
![image](https://github.com/holepunchto/bare-dev/assets/64911460/13046c09-7d11-48d8-b2e6-d49597ff29a0)

Not sure if my hacking has fked something up or if my multiple re-runs of `hello-pear --configure` has made something break. Anyways hope this issue might help somebody else who got stuck 👍

**Comment by kasperisager** [comment]
Thanks for the report! I fixed the `shell` option, that's indeed needed when executing batch scripts on Windows. The rest seem environment specific though, I couldn't reproduce those. In particular the mirroring can be slow depending on where you are in the world as it downloads a pretty substantial amount of data from the swarm.

**Comment by kasperisager** [comment]
Had to roll back the `shell` option default as it breaks command arguments.

**Comment by n9lsjr** [comment]
Ok 👍 The mirror / downloading worked btw 🎉

**Comment by n9lsjr** [comment]
I think that was a problem for me too when I added shell : true to all exec, spawn etc. It was only needed in the end to start en sdk.manager process with execFile 👍 

> Had to roll back the `shell` option default as it breaks command arguments.
